language: generic

# Dependency of the minted package
before_install:
  - sudo apt-get install python-pygments

install:
  - source ./texlive/texlive_install.sh

#cache:
#  directories:
#    - /tmp/texlive
#    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR

script:
  - pdflatex --shell-escape ./main.tex
before_deploy:
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
    - ./main.pdf
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: true
